import{a as S,S as q,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="50639932-bade7ab2566f2f706b9ab2c5d",M="https://pixabay.com/api/",R=15;async function p(o,t=1){const s={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:t};return(await S.get(M,{params:s})).data}const h=document.querySelector(".loader"),y=document.querySelector(".gallery"),g=document.querySelector(".load-more");let d=null;function b(){h.classList.remove("visually-hidden")}function u(){h.classList.add("visually-hidden")}function $(){y.innerHTML=""}function L(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:E,downloads:P})=>`
    <li class="gallery-item">
      <a href="${a}">
        <img src="${s}" alt="${e}" />
      </a>
      <div class="cont">
        <p><b>Likes</b><br>${r}</p>
        <p><b>Views</b><br>${n}</p>
        <p><b>Comments</b><br>${E}</p>
        <p><b>Downloads</b><br>${P}</p>
      </div>
    </li>`).join("");y.insertAdjacentHTML("beforeend",t),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){g.classList.remove("visually-hidden")}function w(){g.classList.add("visually-hidden")}function O(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const m=document.querySelector(".form"),x=document.querySelector(".load-more");let c="",i=1,f=0;m.addEventListener("submit",async o=>{if(o.preventDefault(),$(),w(),b(),c=o.target.elements["search-text"].value.trim(),i=1,!c)return u(),l.error({title:"Error",message:"Please enter a search term.",position:"topRight"});try{const t=await p(c,i);if(f=t.totalHits,t.hits.length===0)return l.error({title:"Error",message:"No images found. Please try another query.",position:"topRight"});L(t.hits),f>i*15&&v()}catch{l.error({title:"Error",message:"Failed to fetch images.",position:"topRight"})}finally{u(),m.reset()}});x.addEventListener("click",async()=>{i+=1,b(),w();try{const o=await p(c,i);L(o.hits),O();const t=Math.ceil(f/15);i<t?v():l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{l.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{u()}});
//# sourceMappingURL=index.js.map
